config/routes.rb
Rails.application.routes.draw do
  resources :restaurants #, except: [:index, :show]
  get 'restaurants/whatever', to: 'restaurants#whatever', as: :whatever_restaurant
  # # verb 'path', to: 'controller#action'

  # # See all restaurants
  # get 'restaurants', to: 'restaurants#index', as: :restaurants

  # # Create a restaurant
  # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant

  # # See details about one restaurant
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # post 'restaurants', to: 'restaurants#create' #, as: :restaurants

  # # Update a restaurant
  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  # patch 'restaurants/:id', to: 'restaurants#update'
  # put 'restaurants/:id', to: 'restaurants#update'

  # # Destroy a restaurant
  # delete 'restaurants/:id', to: 'restaurants#destroy', as: :destroy_restaurant
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show ; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      # flash[:notice] = ""
      render 'new'
    end
  end

  def edit;end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :address)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord777</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>The Spoon 777</h1>

<ul>
  <% @restaurants.each do |r| %>
    <li>
      <%#= link_to r.name, restaurant_path(id: r.id) %>
      <%#= link_to r.name, restaurant_path(r) %>
      <%= link_to r.name, r %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1>
  <%= @restaurant.name %>
</h1>

<p><%= @restaurant.address %></p>
<p><%= '🔥' * @restaurant.rating if @restaurant.rating.present? %></p>

<%= link_to 'edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'delete', restaurant_path(@restaurant), method: :delete, data: { confirm: "You sure you want to delete this restaurant?" } %>